config/routes.rb
Buzz::Application.routes.draw do

	resources :alerts do 
   		resources :comments
		resources :discusions
        end
        root :to => "alerts#new"

end

app/models/alert.rb
class Alert < ActiveRecord::Base
require 'twitter_search'

has_many :comments
has_many :discusions
attr_accessible :content, :lugar
validates_presence_of :content

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :alert
  attr_accessible :content
  validates_presence_of :content
  validates_length_of :content,:maximum => 400

end

app/models/discusion.rb
class Discusion < ActiveRecord::Base

attr_accessible :content
belongs_to :alert
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController

  def index
  
  end

  def show
    @alert = Alert.find(params[:id])
    @comentarios = @alert.comments.find(:all, :order => 'created_at DESC').paginate(:per_page => 3, :page => params[:page])
    #@comentarios = @alert.comments.all
  end

  def create
  @alert = Alert.new params[:alert]
  if @alert.save
  redirect_to new_alert_path 
  else
  @alertas= Alert.all.reverse!
  client = TwitterSearch::Client.new('buzz')
  @twets = client.query(:q => 'from:traficoentegus')
  @alertas = Alert.find(:all, :order => 'created_at DESC').paginate(:per_page => 3, :page => params[:page])
  render :new
  end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def new
  @alert = Alert.new 
  @alertas= Alert.all.reverse!
  @alertas = Alert.find(:all, :order => 'created_at DESC').paginate(:per_page => 3, :page => params[:page])
 
  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def show
  end

  def new
  @alert= Alert.find(params[:alert_id])
  @comment = Comment.new
  @comment.alert_id = @alert.id
  @comment.alert=@alert
  end

  def create
    @alert= Alert.find(params[:alert_id])   
     @comment = Comment.new(params[:comment])
     @comment.alert= @alert
     @comment.alert_id = @alert.id
    if  @comment.save
   redirect_to alert_path(@alert)
   else
    render :new
   end
  end

  def update
  end

  def edit
  end

  def destroy
  end

end

app/controllers/discusions_controller.rb
class DiscusionsController < ApplicationController
  def index
  end

  def show
  end

  def create
    @alert= Alert.find(params[:alert_id])   
    @discuss = Discusion.new(params[:discuss])
    @discuss.alert_id = @alert.id
    if @discuss.save
   redirect_to alert_path(@alert)
   else
    render :new
   end
  end

  def new
  @alert= Alert.find(params[:alert_id])
  @discuss = Discusion.new
  @discuss.alert_id = @alert.id
  end

end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discusions_helper.rb
module DiscusionsHelper
end

app/views/alerts/create.html.erb
<h1>Alerts#create</h1>
<p>Find me in app/views/alerts/create.html.erb</p>

app/views/alerts/destroy.html.erb
<h1>Alerts#destroy</h1>
<p>Find me in app/views/alerts/destroy.html.erb</p>

app/views/alerts/edit.html.erb
<h1>Alerts#edit</h1>
<p>Find me in app/views/alerts/edit.html.erb</p>

app/views/alerts/index.html.erb
<h1>Alerts#index</h1>
<p>Find me in app/views/alerts/index.html.erb</p>
<%=semantic_form_for(@alert) do |f|%>
<%=f.inputs%>
<%=f.buttons%>
<%end%>

app/views/alerts/new.html.erb
<div class= "dias">
<%=semantic_form_for @alert do |f|%>
<%=f.inputs do%>
<p>
<h4><%=f.input :lugar, :label => "Ponle un titulo a tu duda!!"%></h4>
<h4><%=f.input :content, :as => :text,:input_html => { :rows => 3 }, :label => "Que es lo que no sabes???" %></h4></p>
<%end%>

<% f.buttons do %>
<h2><%= f.commit_button "Enviar Duda!!!" %></h2>
<% end %>

<%end%>

<br/>

<%= will_paginate @alertas%>

<%@alertas.each do |t|%>
<span class ="contenta">
<h2 class="star"><%=t.lugar%></h2>
<p><%=t.content%></p> 
<p><%=link_to  "Ver Duda!! ", alert_path(t)%> created: <%=distance_of_time_in_words DateTime.now, t.created_at%> ago. <%=link_to "Sabes la respuesta?? COMENTALO!!", new_alert_comment_path(t.id)%></p>
</span>
<br/>
<%end%>


</div>

app/views/alerts/show.html.erb
<div class= "dias">

<div id="wrap">
  <div id="col1">
    <h1 class = "13"><%=@alert.lugar %></h1>
    <h2 class = "16"><%= @alert.content%></h2>
    <!--<input type="button" value="Geocode" onclick="codeAddress()">-->
   <h1>Comentarios</h1>
    <%if @comentarios.blank?%>
      <p>No hay respuestas todavía. <%=link_to "Se el primero!", new_alert_comment_path(@alert.id)%></p>
    <%else%>
      <ul>
	  <%@comentarios.each do |t|%>
	      <li class = "nones"><h2 class="star"><%=t.content%></h4></li>
	      <br/>
	  <%end%>
      </ul>
      <%= will_paginate @comentarios%>
      <p><%=link_to "Tienes una mejor respuesta!  COMENTA!! .", new_alert_comment_path(@alert.id)%></p>
    <%end%>
  </div>
  
</div>
</div>

app/views/alerts/update.html.erb
<h1>Alerts#update</h1>
<p>Find me in app/views/alerts/update.html.erb</p>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<div class= "dias">
<h1>Responder a la pregunta:</h1>
<h3><%=link_to @alert.lugar, alert_path(@alert) %></h3>

<%=semantic_form_for [@alert,@comment] do |f|%>
<%=f.inputs do%>
<%=f.input :content, :as => :text,:input_html => { :rows => 3 }, :label => "Escribí tu Comentario"%>
<%end%>

<% f.buttons do %>
<%= f.commit_button "Envia tu respuesta gueek! XD" %>
<% end %>

<%end%>

</div>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/discusions/create.html.erb
<h1>Discusions#create</h1>
<p>Find me in app/views/discusions/create.html.erb</p>

app/views/discusions/index.html.erb
<h1>Discusions#index</h1>
<p>Find me in app/views/discusions/index.html.erb</p>

app/views/discusions/new.html.erb
<h1>Create Comment</h1>

<%=semantic_form_for [@alert,@discuss] do |f|%>
<%=f.inputs do%>
<%=f.inputs :contenido%>
<%end%>
<%=f.buttons%>
<%end%>

app/views/discusions/show.html.erb
<h1>Discusions#show</h1>
<p>Find me in app/views/discusions/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pregunte, No Invente!!!!</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link href="/Vertigo/style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/Vertigo/js/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="/Vertigo/js/script.js"></script>
<script type="text/javascript" src="/Vertigo/js/cufon-yui.js"></script>
<script type="text/javascript" src="/Vertigo/js/arial.js"></script>
<script type="text/javascript" src="/Vertigo/js/cuf_run.js"></script>
  <link href="http://fonts.googleapis.com/css?family=Reenie+Beanie" rel="stylesheet" type="text/css"/>


 <link rel="stylesheet" href="/themes/default/default.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/themes/pascal/pascal.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/themes/orman/orman.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/nivo-slider.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/demo/style.css" type="text/css" media="screen" />

  <link href='http://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'> 
  
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no"/>
<link href='http://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet' type='text/css'>

</head>

<body>

<div class="main">
  <div class="header">
    <div class="header_resize">
      <div class="logo">
        <h1><a href="/alerts/new">Just<span>ASK</span><small>Si no lo sabe, PREGUNTE!!</small></a></h1>
      </div>
      <div class="menu_nav">
        <ul>
          <li><a href="/alerts/new">Home</a></li>
          <li><a href="/alerts/new">Departamento IT</a></li>
        </ul>
      </div>
      <div class="clr"></div>
      <div class="clr"></div>
      </div>
    </div>
       <div id="wrapper">
   
        <div class="slider-wrapper theme-default">
            <div class="ribbon"></div>
            <div id="slider" class="nivoSlider">
                <img src="/demo/images/toystory.jpg" alt="" />
                <a href="http://dev7studios.com"><img src="/demo/images/up.jpg" alt="" /></a>
                <img src="/demo/images/walle.jpg" alt="" />
                <img src="/demo/images/nemo.jpg" alt="" title="#htmlcaption" />
            </div>
            
  

    </div>


    </div>
     <br/>
      <br/>
    
    <div class="clr"></div>
  </div>
<div class="topo">  
<div class="content">
    <div class="mainbar">
   
   <%=yield%>  
     
    </div>
    <div class="sidebar">
      <div class="gadget">
        <div class="search">
          <form method="get" id="search" action="#">
            <span>
            <input type="text" value="Search..." name="s" id="s" />
            <input name="searchsubmit" type="image" src="/Vertigo/images/search.gif" value="Go" id="searchsubmit" class="btn"  />
            </span>
          </form>
          <div class="clr"></div>
        </div>
      </div>
    <div class="gadget">
        <h2 class="star"><span>Sidebar</span></h2>
        <div class="clr"></div>
        <ul class="sb_menu">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Preguntas Frecuentes</a></li>
          <li><a href="#">Direccion IT</a></li>
          <li><a href="#">Amenazas Actuales</a></li>
        </ul>
      </div>
     
    </div>
    <div class="clr"></div>
  </div>
</div>

</div>
</div>
 <script type="text/javascript" src="scripts/jquery-1.6.1.min.js"></script>
    <script type="text/javascript" src="../jquery.nivo.slider.pack.js"></script>
    <script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
    </script>
</body>
</html>